### ISSUE TITLE
affine does not exist in nibabel 1.3, it's get_affine, which is deprecated

### ISSUE THREAD

**Issue by samuelstjean** [daducci/COMMIT#1]
I tried to run the example, but it assumes the nibabel 2.0 command for the affine (without expliciting the version requirements in the install). The old 1.0 way of doing it is get_affine, but that is deprecated according to http://nipy.org/nibabel/reference/nibabel.spatialimages.html

So, as a workaround, I suggest either

+ putting nibabel 2.0 as a dependency
+ checking for nibabel version with nibabel.__version__ and use affine for 2.0 (like it is currently doing) and use get_affine for nibabel 1.

Second option won't force people to upgrade, but requires some code edit.

**Comment by daducci** [comment]
Thanks @samuelstjean for testing!
I'm really new in Python, but I guess now the issue should be fixed.

**Comment by samuelstjean** [comment]
Yes, it works now, thanks.
