### ISSUE TITLE
Segmentation when trying to create the dictionary from tractogram

### ISSUE THREAD

**Issue by martcous** [daducci/COMMIT#11]
Hi,

I've been trying to run this and I get a Segmentation fault during the "Exporting EC compartments" step while creating the dictionary from the tractogram. Do you have any idea how to debug this?

I saw that you had a COMMIT debugger. In order to compile it I had to add the flag -std=c++11 to the CMakeLists, but now when I run it I instantly get a seg fault... I am on Ubuntu 14.04.

If you have time, I can email you my data.

Thanks a lot,
Martin

**Comment by martcous** [comment]
Quick update: I somehow had missed your documentation of the COMMIT_Debugger, sorry about that. However, my problem persists.

**Comment by barakovic** [comment]
Hello Martin,
     did you run the demo on the Lausanne data? Do you have problem on the "Exporting EC compartments" also there?

The COMMIT Debugger is not a tool to debug the code but is a tool where you can visualize your data, check orientations of the peaks and other useful informations about your data.

You can e-mail me your data.

Muhamed

**Comment by martcous** [comment]
Thanks for the reply - yes I did run the whole demo correctly. And of course I understood that the Debugger was for data debugging, but still it would be nice to validate my data.

I'll go ahead and upload my data then, thanks!
