### ISSUE TITLE
From what I see there is no difference between outputs of COMMIT1 and COMMIT2

### ISSUE THREAD

**Issue by komabso** [daducci/COMMIT#113]
Hello.

Before processing all the data using COMMIT2, I tried to compare several values to determine which regularization lambda and fiber shift to use.

However, even if the value of Lambda is changed (applying anatomic priors), the results of the binary connectome of COMMIT1 and COMMIT2 seemed to be almost no difference, so I am inquiring about it.

The code What I used is below.
[test_lambda.txt](https://github.com/daducci/COMMIT/files/8965317/test_lambda.txt)

The first two pictures below are the binary connectome of COMMIT1 and COMMIT2 with fiber shift of 0.5 and lambda of 0.5 using one of the data I will process. The upper is COMMIT1 and the lower is COMMIT2.

The next two pictures are duplications that I followed the COMMIT2 tutorial that you wrote. The upper is COMMIT1 and the lower is COMMIT2.

![image](https://user-images.githubusercontent.com/83950926/175250118-5fde5f1d-6cfc-4153-8487-30f4038c79d0.png)
![image](https://user-images.githubusercontent.com/83950926/175250097-4c2af5af-f8e7-4eae-87a0-6f9675727534.png)

![image](https://user-images.githubusercontent.com/83950926/175252049-8e36f2b4-22a9-47b5-a4c2-54af46bd0cf0.png)
![image](https://user-images.githubusercontent.com/83950926/175252069-033ffe32-768d-4eb6-bba5-9fec30e466a6.png)

From what I see, the results of your tutorial have difference (COMMIT2 is sparser) but the results of my data don't.

Could you give me some advices? It will be helpful!
And I'm sorry to bother you again 😭 

Best,
Joseph.

**Comment by komabso** [comment]
Thanks, Ale!

1. I subtracted `mit.get_coeffs( get_normalized=False )`, because the error below.

![image](https://user-images.githubusercontent.com/83950926/175326430-3176358d-dd97-45b2-9e79-b193e5279580.png)

Could you give me a way to solve it?

2. You said that "the value for reg_lambda used in this example is only an empirical value for the purpose of this demo" in your COMMIT2 tutorial. How did you decide the empirical value? Could you tell me your know-how?

Although the questions are stupid somewhat, cut me some slack 🙇 

Best,
Joseph.

**Comment by daducci** [comment]
1. Which version of COMMIT are you using? I suspect you are on an old one.
2. We usually increase `lambda` until we see that the density of the resulting connectome actually decreases, and we stop when we notice that too many bundles are remove (I mean, by inspecting the resulting tractograms with the help of an expert neurologist).

**Comment by komabso** [comment]
Hello, Ale!

I used 1.4.6 version. I upgraded commit to latest version, then I could use `mit.get_coeffs( get_normalized=False )`.

However, the result is the same even if lambda is 1. (COMMIT2 and COMMIT1's connectomes look like same.) 😢 
Is Maximum of lambda 1, isn't it?

Best,
Joseph.

**Comment by daducci** [comment]
Lambda can take any value >= 0, and the higher it is, the sparser the matrices should be. Do you get meaningful results when running the COMMIT2 demo (using same data and code)?

**Comment by komabso** [comment]
I appreciate Ale!

Thanks to you, I found the difference between us.
When I ran `tck2connectome`, I used `demo01_fibers.tck`. However, you used `demo01_fibers_connecting.tck`.
When I used `demo01_fibers_connecting.tck`, I got same results as your demo. 😄 

Because `demo01_fibers.tck` and `demo01_fibers_connecting.tck` look same in appearance, I was totally confused about what I have to use.

Thank you very much for your help. 👍 

Best,
Joseph.

**Comment by komabso** [comment]
Hi, @daducci .
I'm sorry to bother you agian.

Unlike your demo (already mentioned, I duplicated it), when I applied commit2 to my data, it seemed that commit2 has no effect.
According to your advice, I used connected_fibers.tck, but the binary connectomes looks like same.
Left is commit1 and right is commit2.

![image](https://user-images.githubusercontent.com/83950926/179666730-f92ea7af-0f33-48de-beea-cc853a1b2e8f.png)

The code which I used is below.

[test_commit2.txt](https://github.com/daducci/COMMIT/files/9137565/test_commit2.txt)

Could you see where the problem is?

Best,
Joseph.

**Comment by komabso** [comment]
Yes. 
To decide proper lambda, I had a test where lambdas are [0, 5e-1, 5e-2, 5e-3, 5e-4, 5e-5, 5e-6].

But all connectomes looked like same.

![image](https://user-images.githubusercontent.com/83950926/179735820-37971b02-e697-4d86-8e94-5e90a2585aa5.png)

As the figure is from 1 to 7, the lambda becomes smaller.

Best,
Joseph.

**Comment by daducci** [comment]
Could you perform a last test using a very large lambda, for instance `lambda=1e2`or `lambda=1e5`?

Otherwise, the problem could be that you have a very high number of ROIs in your parcellation (around 400), and thus the regularization on bundles might not be very effective? Let's see the results of this test.

PS: in case, would it be possible for you to share (privately) your data so that we can perform some tests and understand better what is going on?

**Comment by komabso** [comment]
Okay.

At first, I will do the test on your advice.

And then if there are same results, I will send my data to you.
Please give me any contact way. (e.g. email, and so forth...)

Best,
Joseph.

**Comment by komabso** [comment]
Hi!

Even though I ran the last test using very large lambdas (100, 1000, 10000), the results were same (no effect).

Here is the data file link.
https://drive.google.com/drive/folders/1T2W9mWxjXZdCPPp3KhsSlfwMoQsj3qf2?usp=sharing

Could you check it out?

Best,
Joseph.

**Comment by MarioOcampo** [comment]
Dear @komabso 

I did a test using your dataset, the results of COMMIT2 and COMMIT1 are different, but similar. 

Some notes that can explain the similitude of the results. 

- The original tractograme has 3.3M streamlines, after the execution of COMMIT1 only 0.7M have non-zero contribution, and only the groups of those are used by COMMIT2. After that, not many groups of streamlines are removed, because the signal may not be well explained with fewer streamlines.  
- The original connectome is sparse, its density is 0.17, after COMMIT1 0.13 similar for COMMIT2. 

I am not familiar with the parcellation you are using, and I do not know if the density of the original connectome has to be reduced more than that. 

Best regards
Mario

**Comment by komabso** [comment]
Thank you for helping me even though you are busy!👍 

 Do you think the result is one of the proper results of commit2 or not? (maybe the latter 😢 )
 Is there anything else I can do?
 
 Best regards
 Joseph.
