### ISSUE TITLE
Peak Orientation

### ISSUE THREAD

**Issue by steso** [daducci/COMMIT#22]
Hi
In COMMIT, it seems like the peak orientation is expected to be in voxel coordinates (similar to the current interpretation of the scheme file), however if the nifti header contains an affine transformation with a rotational component (e.g. a rotated FOV in the scanner), peak-files generated with MRtrix will not be interpreted correctly. Conversely, if e.g. dipy is used, the peak orientation is assumed to be in voxel-coordinates (instead of world coordinates) and are therefore interpreted correctly in trk2dictionary and in the COMMIT_debugger. 
It might be beneficial to clarify the used conventions and/or add an additional flag to enable users to apply the affine transformation in trk2dictionary. Furthermore, it might be helpful to also state in the documentation that the scheme-file is expected to contain gradient directions in the voxel-coordinate system.

**Comment by daducci** [comment]
Fixed by PR #23
