### ISSUE TITLE
Update demo "Getting started"

### ISSUE THREAD

**Issue by barakovic** [daducci/COMMIT#27]
Following the last improvement of the code and due to the rotation in the affine of the `DWI.nii` the demo should use `peaks_use_affine = True`.

```
from commit import trk2dictionary
trk2dictionary.run(
    filename_trk   = 'LausanneTwoShell/fibers.trk',
    path_out       = 'LausanneTwoShell/CommitOutput',
    filename_peaks = 'LausanneTwoShell/peaks.nii.gz',
    filename_mask  = 'LausanneTwoShell/WM.nii.gz',
    fiber_shift    = 0.5,
    peaks_use_affine = True
)
```

Furthermore will be good to double check how the peaks and the tractography was generated.
In that case of `mrtrix`, in order to avoid problems in the orientation, the best option is to import the gradient table with the option `-fslgrad`.

**Comment by daducci** [comment]
@barakovic , is this issue addressed then? Can we close it?

**Comment by barakovic** [comment]
We need to check how the tractography was generated. The data of the demo contains an affine with a rotation. 
It is possible that exist an error in the orientation if the affine was not considered properly. 
If peaks and tractography were generated with mrtrix with the original bvals and bvecs and the option -fslgrad then everything is ok. 
If were generated with mrtrix with the grad scheme similar as implemented in AMICO, which not consider the affine, and the option -grad from mrtrix, then there is probably an error of rotation in the peaks and in the tractography.
