### ISSUE TITLE
probabilistic fiber tracking of FSL 

### ISSUE THREAD

**Issue by behnam12** [daducci/COMMIT#39]
Hi there ,

I tried with global fiber tracking and deterministic fiber tracking as  input for COMMIT and It worked well.
I am wondering whether it is possible to use probabilistic fiber tracking of FSL (**fdt_paths.nii**) as an input for COMMIT?

Best
Behnam

**Comment by barakovic** [comment]
Hello Behnam,
    COMMIT works with streamline tractography, hence, we cannot have a NIfTI format as input for the tractography. In general, COMMIT can be used with any tractography algorithm that can be converted to the format `.trk`.
Hope this can help to answer your question.

Cheers,

Muhamed
