### ISSUE TITLE
backward compatibility of group structure

### ISSUE THREAD

**Issue by matteofrigo** [daducci/COMMIT#40]
With PR #36 I introduced a bug regarding the backward compatibility of group sparsity. The conversion from a list of lengths of groups for the ordered tractogram to the required np.array is wrong.

Avoid using the ordered group structure until this issue is not solved. If you need to use group sparsity you can follow the example in the [dedicated tutorial](https://github.com/daducci/COMMIT/blob/master/doc/tutorials/AdvancedSolvers/tutorial_solvers.ipynb).

**Comment by daducci** [comment]
Closed by #38
