### ISSUE TITLE
Optic chiasm data as input  for COMMIT

### ISSUE THREAD

**Issue by behnam12** [daducci/COMMIT#44]
Dear COMMIT group ,

I used COMMIT for whole human brain and the results were great.
Now, I am going to use COMMIT framework  for ex-vivo optic chiasm data. But, the result does not look reasonable and Intracellular compartment map does match to Mask or DWI as can be seen in the attached image. I adjusted the parallel  and perpendicular diffusivity for ex-vivo condition and checked  the inputs  for COMMIT (fibers, peaks, mask) but I could not find the reason for it. 

I appreciate for any idea or suggestion about this problem.
Is it possible to send my data for more accurate evaluation ?

Best
Behanm

![opticcaism](https://user-images.githubusercontent.com/19838125/37873325-a220e712-2fcf-11e8-987c-34c2a5d7b7cd.jpg)

**Comment by barakovic** [comment]
Hello Behnam,
     sorry for the late answer. You may want to send me the data so I can check if there are technical problems. I would also like to ask you what are the results that you are hoping to have from the IC map (density in the crossing higher?). 
Cheers, 
Muhamed

**Comment by behnam12** [comment]
Hello Muhamed ,

Thank you for your response.
firstly, It would be great if I can find out why IC map does not match with whole DWI data set.
I want to have IC map for whole optic chiasm (diffusion data) and then look at how it changes between different regions.
I've sent my data to you via E-mail.

Thanks
Behnam

**Comment by barakovic** [comment]
The problem is that tractography and DWI are not aligned. A wrong conversion from ".tck" to ".trk" was done.
![problem](https://user-images.githubusercontent.com/9309757/38318647-20011a5e-3830-11e8-8854-04669dda5c1c.png) (image with COMMIT_debugger)

Here a possible solution; a tool that converts properly different formats: https://github.com/MarcCote/tractconverter

Cheers,

Muhamed

**Comment by behnam12** [comment]
Hi Muhamed ,

Thanks for your response and advice. I'll try it.

Best
Behnam

**Comment by behnam12** [comment]
Hi Muhamed ,

I just want to inform you that tractconvertor works successfully.


Best
Behnam
