### ISSUE TITLE
Wrong structureIC, if all groups have the same number of streamlines

### ISSUE THREAD

**Issue by MarioOcampo** [daducci/COMMIT#53]
For the case: ` normIC == group_sparsity` and `group_is_ordered == True`.
The streamlines (in the .trk file) are sorted by group and the input `structureIC`  contains the number of elements per group. If all groups have the same number of streamlines,  the following error occurs when the function `fit` is executed:
```
commit/proximals.pyx in commit.proximals.prox_group_sparsity()
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
```

**Comment by daducci** [comment]
Fixed because we removed a deprecated function, i.e. `is_sorted`
