### ISSUE TITLE
/usr/include/stdio.h issue

### ISSUE THREAD

**Issue by mdesco** [daducci/COMMIT#58]
Hi all. 

This is not an issue because I solved it but it might be helpful for other Mac Users when installing commit. With new Mac, you might get this error when running pip install . 

/Users/desm2239/anaconda2/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1

This is because your stdio.h is not in your /usr/include when Xcode installs stuff.

Now, on top of this, you cannot create a symlink or a directory in /usr/include. New MacOSX, after El Capitan block you. 

So, you must disable SIP: https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x

Next, you can create a symlink /usr/include using something like this.
find /Applications/Xcode.app -name stdio.h
sudo ln -sf /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ /usr/include

pip install . 
should now work!

Hope this helps others...

**Comment by daducci** [comment]
I've never seen this problem happening anymore, so I will close this issue now.
