### ISSUE TITLE
Commit is not compatible with Dipy 1.0

### ISSUE THREAD

**Issue by jchoude** [daducci/COMMIT#61]
This is the same issue as in AMICO (https://github.com/daducci/AMICO/pull/89). Dipy 1.0 drops support for python 2, and therefore removes the `dipy.utils.six` module and functions.

The same fixes should be applied as in AMICO.

**Comment by daducci** [comment]
This should be fixed now, isn't it?

**Comment by jchoude** [comment]
Following your PRs, I think so.

I don't know if it's exactly related, but if I create a simple virtual environment, then install the basic dependencies (numpy, scipy, nibabel, dipy, amico), then do as said in the doc:

`pip install .`

when I try to `import commit`, I get a 

`ModuleNotFoundError: No module named 'commit.core`

Not sure if it's my setup, it worked at some point before.

Do you know what could be happening?

**Comment by daducci** [comment]
Usually that means that the cython compilation failed..

**Comment by MarkNelson86** [comment]
I am having this problem as well: "ModuleNotFoundError: No module named 'commit.core". I've check and Cython is installed (import cython works). How did you solve it?

**Comment by MarioOcampo** [comment]
Hello, 
Check that the terminal is not in the installation folder.

**Comment by MarkNelson86** [comment]
Hi Mario,

  Now import commit works, but none of the commit modules work:

AttributeError: module 'commit' has no attribute 'core'
AttributeError: module 'commit' has no attribute 'Evaluation'

________________________________

**Comment by MarioOcampo** [comment]
Hello Mark, 
Looks like there is a problem with the installation. 
did you try `pip install dmri-commit`
Or do you get any messages after the installation? are you using an environment?

**Comment by MarkNelson86** [comment]
Good morning,

 I re-installed everything from scratch again this morning and it worked this time. Not sure what I did wrong before. Thanks for your help.

Mark
________________________________

**Comment by MarioOcampo** [comment]
Hello Mark, 

good to know that the program is working properly, thank you for telling us about the problem. Please let us know if you have any other problems with the software. 

Best.
Mario

**Comment by daducci** [comment]
Are you sure you didn't download the code from github and, then you installed COMMIT via `pip install dmri-commit` but the open the python shell from there? If so, then when you issue the command `import commit`, the system will try to import from the current folder (which is not compiled). Not sure if this was the case, though..

**Comment by MarkNelson86** [comment]
Hi Alessandro,

  Thanks for your tip. I used a venv to straighten things out. I also realized that I didn't need to append path/to/COMMIT_clone to PYTHONPATH. I did this initially (I am used to Matlab), and it caused problems.

  Everything is working fine now. I'm excited to see what this can do!

Thanks,
Mark
________________________________
