### ISSUE TITLE
Verbose parameter should be bool

### ISSUE THREAD

**Issue by daducci** [daducci/COMMIT#90]
In the `fit()` function (and all functions inside `solvers.py` called from there) the parameter `verbose` is an integer whose value is `0` or `1`, and its value is checked as `if verbose>=1`. I think it would be more intuitive to set `verbose` to be a boolean.

**Comment by MarioOcampo** [comment]
Yes, for the actual functionality, it could be more intuituve. 
If it is `integer`, it could have different levels of display, like `None`, `important_steps` (start, end), `every_iteration`, and others. But right now I think this is not implemented. This type of behavior can be implemented with modules like `logging`.

**Comment by daducci** [comment]
No, indeed, at the moment it is actually binary (yes or no) but implemented as an `integer`, which could introduce ambiguities. What if we change it to `bool` for the time being?

**Comment by MarioOcampo** [comment]
I think the change is possible, and this should not break actual pipelines.  
Later we can think to have levels of verbose ([logging](https://docs.python.org/3/howto/logging.html))

**Comment by daducci** [comment]
I agree, let's keep this in mind. Can you create a PR to implement this small modification? No need to update the version, just the changelog

**Comment by daducci** [comment]
Clsoe by #96
