### ISSUE TITLE
see an error in trk2dictionary 

### ISSUE THREAD

**Issue by mohammadhadiarabi** [daducci/COMMIT#95]
Dear Developer,
When I run step by step codes based on wiki page, I see an error:
>>> trk2dictionary.run(
...     filename_tractogram = 'demo01_fibers.tck',
...     filename_peaks      = 'peaks.nii.gz',
...     filename_mask       = 'WM.nii.gz',
...     fiber_shift         = 0.5,
...     peaks_use_affine    = True
... )
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "commit/trk2dictionary/trk2dictionary.pyx", line 27, in commit.trk2dictionary.run
  File "commit/trk2dictionary/trk2dictionary.pyx", line 108, in commit.trk2dictionary.run
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

I would be appreciated if you help me to fix this error.
Best,
Mohammad

**Comment by MarioOcampo** [comment]
Hello @mohammadhadiarabi , 

thanks for letting us know about this problem.
I'm trying to reproduce the error. What version of Python and COMMIT are you using? 
To obtain the version of  COMMIT you can execute:
```
import commit
commit.__version__
```
Best

**Comment by daducci** [comment]
Also, did you install it with `pip install dmri-commit` or via the sources?

**Comment by mohammadhadiarabi** [comment]
Thank you for rapid response. I use Ubuntu18.04 and  '1.3.9.4' version of COMMIT.
 I installed with pip3 install dmri-commit
Best,
Mohammad

**Comment by MarioOcampo** [comment]
Could you update COMMIT? 
`pip3 install dmri-commit --upgrade`

**Comment by mohammadhadiarabi** [comment]
I updated COMMIT, but I again see the error

**Comment by MarioOcampo** [comment]
In version 1.3.9.4 the error you reported happened when the tractogram was not found. 
In version 1.4.4, if the tractogram is not found it shows the message `[ ERROR ] Tractogram file not found` 

Could you confirm that you have the version 1.4.4 and the tractogram file. 
If that is OK, could you share with us the new error message.

**Comment by mohammadhadiarabi** [comment]
Dear Mario,
Thank you for your help. It works now. 
Tnx
